- copy:
   src: /var/lib/libvirt/images/linux.qcow2
   dest: /var/lib/libvirt/images/lb2.qcow2
   remote_src: true
- copy:
   src: /var/lib/libvirt/images/linux.qcow2
   dest: /var/lib/libvirt/images/web3.qcow2
- copy:
   src: /var/lib/libvirt/images/linux.qcow2
   dest: /var/lib/libvirt/images/web4.qcow2
